services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        OpenLoyalty\Bundle\SettingsBundle\Provider\ChoiceProvider:
            tags:
            - { name: ol.settings.choices }

    OpenLoyalty\Bundle\SettingsBundle\Service\GeneralSettingsManagerInterface: '@OpenLoyalty\Bundle\SettingsBundle\Service\GeneralSettingsManager'
    OpenLoyalty\Bundle\SettingsBundle\Service\SettingsManager: '@OpenLoyalty\Bundle\SettingsBundle\Service\GeneralSettingsManager'

    OpenLoyalty\Bundle\SettingsBundle\Provider\:
        resource: '../../Provider/*'

    OpenLoyalty\Bundle\SettingsBundle\Service\:
        resource: '../../Service/*'

    OpenLoyalty\Bundle\SettingsBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags: ['form.type']

    OpenLoyalty\Bundle\SettingsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    OpenLoyalty\Bundle\SettingsBundle\Validator\Constraints\:
        resource: '../../Validator/Constraints/*'
        tags: ['validator.constraint_validator']

    OpenLoyalty\Bundle\SettingsBundle\Service\FileBasedTranslationsProvider:
        arguments:
            $filesystem: '@ol.settings.frontend_translations_filesystem'
            $fallbackFile: '%fallback_frontend_translations_file%'

    OpenLoyalty\Bundle\SettingsBundle\Service\ConditionsUploader:
        arguments: ['@oloy.settings.uploads_filesystem', '%frontend_customer_panel_url%']

    OpenLoyalty\Bundle\SettingsBundle\Service\LogoUploader:
        arguments: ['@oloy.settings.photos_filesystem']

    OpenLoyalty\Bundle\SettingsBundle\Service\TemplateProvider:
        arguments: ['@ol.settings.manager']

    ol.settings.frontend_translations_filesystem:
        class:     Gaufrette\Filesystem
        factory:   ['@knp_gaufrette.filesystem_map', get]
        arguments: ['frontend_translations']
        public: true

    oloy.settings.photos_filesystem:
        class:     Gaufrette\Filesystem
        factory:   ['@knp_gaufrette.filesystem_map', get]
        arguments: ['logo']

    oloy.settings.uploads_filesystem:
        class:     Gaufrette\Filesystem
        factory:   ['@knp_gaufrette.filesystem_map', get]
        arguments: ['uploads']
